### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by yassinMk** [VdoCipher/node-vdocipher#1]
Hello,
when I try to require it `var VdoCipher = require('vdocipher')` , I get this error : 
``` javascript
(function (exports, require, module, __filename, __dirname) { import request from 'request';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by yassinMk** [comment]
when I use this `var VdoCipher = require('vdocipher/lib/vdocipher.js');`
it works fine

**Comment by vibhavsinha** [comment]
@yassinMk Thanks for pointing that out. We had only tested this with es6. It is now corrected.

You can update it to latest and use `require('vdocipher')`

**Comment by acircuit** [comment]
Hi,
After doing npm install -S node-vdocipher. I am not able to import vdocipher. I tried  'require('vdocipher')', 'require('vdocipher/lib/vdocipher.js')' and 'import vdocipher'.  It says : Module not found: Error: Can't resolve 'vdocipher'. I have also updated the entry file for npm : "main": "lib/vdocipher.js". Please help me with this.
